#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5521-web
    bind *:80
    mode http
    balance roundrobin
    server 5521-web-01 100.24.46.107:80 check
    server 5521-web-02 54.237.204.79:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
