#!/usr/bin/env bash
# This script is used to debug the web server
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
if service nginx restart; then kill "$(pgrep nginx | head -1)"; else echo " * nginx is not running"; fi
