#!/usr/bin/env bash
# debugging_made_short 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart && kill "$(pgrep nginx | head -1)" || echo " * nginx is not running"
